# Generated by Django 3.0.2 on 2020-01-19 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('publication_year', models.PositiveIntegerField()),
                ('edition', models.PositiveIntegerField()),
                ('authors', models.ManyToManyField(related_name='books', to='books_app.Author')),
            ],
        ),
    ]
