# Generated by Django 4.0.6 on 2022-07-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_author_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ('name',)},
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Nome')),
                ('edition', models.PositiveSmallIntegerField(verbose_name='Edição')),
                ('publication_year', models.CharField(max_length=4, verbose_name='Edição')),
                ('authors', models.ManyToManyField(to='core.author')),
            ],
        ),
    ]
